package oosdca3;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
import java.awt.Image;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 * The sign up frame of the program
 * @author dawid
 */
public class SignUp extends javax.swing.JFrame {
    String database_URL = "jdbc:mysql://localhost:3306/project";
    String username = "root";
    String dbPassword = "1234";
    /**
     * The constructor for the sign up class
     */
    public SignUp() {
        super("Sign Up");
        setResizable(false);
        initComponents();
        setComponents();
        setImage();
    }

    /**
     * Sets up the county combo box and the date field
     */
    public void setComponents(){
        countyBox.setEnabled(false);
        dateField.setDateFormatString("dd/MM/yyyy");
        Date date = new Date("02/10/2001");
        dateField.setDate(date);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderBtnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        confirmBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();
        confirmPasswordField = new javax.swing.JPasswordField();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        confirmEmailField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        cityField = new javax.swing.JTextField();
        maleBtn = new javax.swing.JRadioButton();
        femaleBtn = new javax.swing.JRadioButton();
        countyBox = new javax.swing.JComboBox<>();
        emailField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        imagePanel = new javax.swing.JPanel();
        logoImage = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        countryBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        dateField = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jLabel3.setText("Confirm Password");

        jLabel4.setText("First Name");

        jLabel5.setText("Last Name");

        jLabel6.setText("Email");

        jLabel7.setText("Phone Number");

        jLabel8.setText("Address");

        jLabel9.setText("City");

        genderBtnGroup.add(maleBtn);
        maleBtn.setSelected(true);
        maleBtn.setText("Male");

        genderBtnGroup.add(femaleBtn);
        femaleBtn.setText("Female");

        countyBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carlow", "Caven", "Clare", "Cork", "Donegal", "Dublin", "Galway", "Kerry", "Kildare", "Killkenny", "Laois", "Leitrim", "Limerick", "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly", "Roscommon", "Sligo", "Tipperary", "Waterford", "Westmeath", "Wexford", "Wicklow" }));

        jLabel12.setText("Confirm Email");

        jLabel13.setText("Date Of Birth");

        logoImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\dawid\\Desktop\\Logo.PNG")); // NOI18N

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanelLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(logoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel11.setText("Gender");

        jLabel14.setText("Country");

        countryBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Poland", "USA", "Ireland" }));
        countryBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryBoxActionPerformed(evt);
            }
        });

        jLabel10.setText("County");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(passwordField)
                                    .addComponent(firstNameField)
                                    .addComponent(lastNameField)
                                    .addComponent(confirmEmailField)
                                    .addComponent(emailField)
                                    .addComponent(usernameField)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(jLabel7))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel13)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(phoneField)
                                            .addComponent(addressField)
                                            .addComponent(cityField)
                                            .addComponent(countryBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(countyBox, 0, 183, Short.MAX_VALUE)
                                            .addComponent(dateField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(73, 73, 73))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(maleBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(femaleBtn)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(countryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleBtn)
                    .addComponent(femaleBtn)
                    .addComponent(jLabel11)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(confirmEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        usernameField.getAccessibleContext().setAccessibleName("");
        usernameField.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        Login login = new Login();
        login.setDefaultCloseOperation ( JFrame.EXIT_ON_CLOSE );
        login.setSize ( 275, 170 );
        login.setVisible ( true );
        login.setLocation ( 500, 400 );
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        if(validateInput()){
            uploadToDB();
            Login login = new Login();
            login.setDefaultCloseOperation ( JFrame.EXIT_ON_CLOSE );
            login.setSize ( 275, 170 );
            login.setVisible ( true );
            login.setLocation ( 500, 400 );
            dispose();
        }
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void countryBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryBoxActionPerformed
        if((countryBox.getSelectedItem()+"").compareTo("Ireland")==0){
            countyBox.setEnabled(true);
        } else{
            countyBox.setEnabled(false);
        }
    }//GEN-LAST:event_countryBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }
    /**
     * Sets the image at the top of the window
     */
    public void setImage(){
       Icon i = logoImage.getIcon();
       ImageIcon icon = (ImageIcon)i;
       Image image = icon.getImage().getScaledInstance(logoImage.getWidth(), logoImage.getHeight(), Image.SCALE_SMOOTH);
       logoImage.setIcon(new ImageIcon (image));
    }
    
    /**
     * Validates each field entered in the sign up window
     * @return boolean
     */
    public boolean validateInput(){
        if(!validateUsername()){
            return false;
        }if (!validatePassword()){
        return false;
        }
        if(!validateFirstName()){
            return false;
        }
        if(!validateLastName()){
            return false;
        }
        if(!validateEmails()){
            return false;
        }
        if(!validatePhone()){
            return false;
        }
        if(!validateAddress()){
            return false;
        }
        if(!validateCity()){
            return false;
        }
        return true;
    }

    /**
     * Validates user name
     * @return boolean
     */
    public boolean validateUsername(){
        boolean output=true;
        String username = usernameField.getText();
        
        if(username.length() == 0){
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(frame, "Username Field is Required");
            output = false;
        }
        return output;
    }
    /**
     * Validates password and the confirm password fields
     * @return boolean
     */
    public boolean validatePassword(){
        boolean output=true;
        String password = passwordField.getText();
        String password2 = confirmPasswordField.getText();
        
        if(password.compareTo(password2)!=0){
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(frame, "The Passwords Don't Match");
            output = false;
        } else if(checkPassword()==false && output==true){
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(frame, "The Password requires 5 letters, 2 numbers and a special character");
            output = false;
        }
        return output;
    } 
    /**
     * Checks whether the password has the required security
     * @return boolean
     */
    public boolean checkPassword(){
        boolean output=false;
        int letterCount=0;
        int numberCount=0;
        int specialCharCount=0;
        String password = passwordField.getText();
        for(int i=0;i<password.length();i++){
            if((password.charAt(i)>='a'&&password.charAt(i)<='z')||(password.charAt(i)>='A'&&password.charAt(i)<='Z')){
                letterCount++;
            } else if(password.charAt(i)>='0' && password.charAt(i)<='9'){
                numberCount++;
            } else if((password.charAt(i)>=33 && password.charAt(i)<=47)||(password.charAt(i)>=58 && password.charAt(i)<=63)
                    ||(password.charAt(i)>=91 && password.charAt(i)<=96
                    ||(password.charAt(i)>=123 && password.charAt(i)<=126))){
                specialCharCount++;
            }
        }
        if(letterCount>=5 && numberCount >= 2 && specialCharCount >=1){
            output=true;
        }
        return output;
    }

    /**
     * Validates First Name Field
     * @return boolean
     */
    public boolean validateFirstName(){
        boolean output=true;
        String firstName = firstNameField.getText();
        
        if(firstName.length() == 0){
            JFrame frame = new JFrame("First Name Field Error");
            JOptionPane.showMessageDialog(frame, "First Name Field is Required");
            output = false;
        }
        return output;
    }
    /** 
     * Validates Last Name Field
     * @return boolean
     */
    public boolean validateLastName(){
        boolean output=true;
        String lastName = lastNameField.getText();
        
        if(lastName.length() == 0){
            JFrame frame = new JFrame("Last Name field Error");
            JOptionPane.showMessageDialog(frame, "Last Name Field is Required");
            output = false;
        }
        return output;
    }

    /**
     * Validates email and confirm email Fields
     * @return boolean
     */
    public boolean validateEmails(){
        boolean output = true;
        String email = emailField.getText();
        String email2 = confirmEmailField.getText();
        
        if(email.compareTo(email2)!=0){
            JFrame frame = new JFrame("Email Field Error");
            JOptionPane.showMessageDialog(frame, "The emails Don't Match");
            output = false;
        } else if(email.compareTo("")==0 && output==true){
            JFrame frame = new JFrame("Email Field Error");
            JOptionPane.showMessageDialog(frame, "The email Field is required");
            output = false;
        }
        return output;
    }

    /**
     * Validates the phone number field
     * @return boolean
     */
    public boolean validatePhone(){
        boolean output = true;
        String phoneNo = phoneField.getText();
        
        if(phoneNo.length()==0){
            JFrame frame = new JFrame("Phone Field Error");
            JOptionPane.showMessageDialog(frame, "Phone number field is required");
            output = false;
        } if(!checkPhone() && output){
            JFrame frame = new JFrame("Phone Field Error");
            JOptionPane.showMessageDialog(frame, "Phone number can only contain numbers and special characters");
            output=false;
        }
        return output;
    }

    /**
     * Checks whether the phone number input has any letters in it
     * @return boolean
     */
    public boolean checkPhone(){
        boolean output = true;
        String phone = phoneField.getText();
        for(int i=0;i<phone.length();i++){
            if((phone.charAt(i)>='a' && phone.charAt(i)<='z')||(phone.charAt(i)>='A' && phone.charAt(i)<='Z')){
                output=false;
            }
        }
        return output;
    }
    /**
     * Validates address field
     * @return boolean
     */
    public boolean validateAddress(){
        boolean output = true;
        String address = addressField.getText();
        
        if(address.length()==0){
            JFrame frame = new JFrame("Address Field Error");
            JOptionPane.showMessageDialog(frame, "Address Field is required");
            output = false;
        }
        return output;
    }

    /**
     * Validates city Field
     * @return boolean
     */
    public boolean validateCity(){
        boolean output = true;
        String city = cityField.getText();
        
        if(city.length()==0){
            JFrame frame = new JFrame("City Field Error");
            JOptionPane.showMessageDialog(frame, "City Field is required");
            output = false;
        }
        return output;
    }
    /**
     *  Uploads entered data to the users database
     */
    public void uploadToDB(){
        String username = usernameField.getText();
        String password = passwordField.getText();
        String firstName = firstNameField.getText();
        String lastName = lastNameField.getText();
        String email = emailField.getText();
        String phone = phoneField.getText();
        String address = addressField.getText();
        String city = cityField.getText();
        String country = countryBox.getSelectedItem()+"";
        String county;
        if(country.compareTo("Ireland")==0){
            county = countyBox.getSelectedItem()+"";
        } else {
            county = "";
        }
        String gender;
        if(maleBtn.getSelectedObjects()!=null){
            gender = "Male";
        } else {
            gender = "Female";
        }
        Date date = dateField.getDate();
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dob = dateFormat.format(date);
        Connection con;
        Statement stm;
        ResultSet result;
        try{
                con = DriverManager.getConnection(this.database_URL,this.username,this.dbPassword);
                stm = con.createStatement();
                stm.executeUpdate("INSERT INTO users "
                        + "( UserName, Password, FirstName, LastName, Email, PhoneNo, Address, City, County, Country, Gender, DateOB)"
                        + " Values (\'"+username+"\', \'"+password+"\', \'"+firstName+"\', \'"+lastName+"\'"
                            + ", \'"+email+"\', \'"+phone+"\', \'"+address+"\', \'"+city+"\'"
                            + ", \'"+county+"\', \'"+country+"\', \'"+gender+"\', \'"+dob+"\')");
        }
        catch(SQLException exc){
            exc.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField cityField;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JTextField confirmEmailField;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JComboBox<String> countryBox;
    private javax.swing.JComboBox<String> countyBox;
    private com.toedter.calendar.JDateChooser dateField;
    private javax.swing.JTextField emailField;
    private javax.swing.JRadioButton femaleBtn;
    private javax.swing.JTextField firstNameField;
    private javax.swing.ButtonGroup genderBtnGroup;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel logoImage;
    private javax.swing.JRadioButton maleBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
